---
version: "3.8"
networks:
  main:

services:
  localstack:
    networks:
      - main
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "./localstack.d/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "./source.jpg:/tmp/source.jpg"

  archiver:
    networks:
      - main
    build:
      context: .
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - S3_SOURCE_BUCKET=source-images
      - S3_DESTINATION_BUCKET=zip-storage
      - SQS_SOURCE_QUEUE=input-queue
      - SQS_DESTINATION=output-queue
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566/
      - AWS_DEFAULT_REGION=eu-west-1
