---
name: "CICD"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    name: "Build container images"
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: "amd64"

      - name: "Get container image tag (git hash)"
        id: short-sha
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: "Checkout Code"
        uses: "actions/checkout@v4"

      - name: Build tag, and push Container Image to Amazon ECR
        id: build-image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: meero-com/archiver:${{ steps.short-sha.outputs.sha8 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          platforms: "linux/amd64"
