---
name: "Github Workflows syntax"

on:
  pull_request:

jobs:
  workflow-validation:
    name: Github Action Workflows validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: reviewdog/action-actionlint@v1
